log_file: inference_log

random_seed: 2022

use_gpu: True
gpu_ids: 1

dataset:
  data_path: "data/test.txt" # 若为空，则为server_inference
  type: json # json/text  json 是整个文件为一个json  text是每行为一个json
  reader:
    type: XXX_reader
    tokenizer: XXX_tokenizer
    vocab_path: "pretrain_model/vocab.txt"
    padding: max_length
    max_seq_len: 512

inference:
  batch_size: 12
  inference_model: "XX_model.pth"
  inference_output: "XXX.result"
