log_file: chip2022_log

random_seed: 2022

use_gpu: True
gpu_ids: 1
# gpu_ids: 0,1 # 自动加载多卡

dataset:
  train:
    data_path: "train.json" # 训练集路径
    type: json  # json/jsonl
    reader:
      type: multi_span_relation_extraction_reader_ce
      tokenizer: bert_tokenizer
      vocab_path: "pretrain_models" # 预训练模型路径
      padding: max_length
      max_seq_len: 512
    batch_size: 12
  dev:
    data_path: "dev.json" # 验证集路径
  test:
    data_path: "testA.json" # 测试集路径

model:
  type: multi_span_relation_extraction_model_ce
  num_labels: 7
  hidden_size: 150
  encoder:
    type: bert
    pretrained_model_dir: "pretrain_models" # 预训练模型路径
  dropout: 0.2

optimizer:
  type: adamw
  lr: 3e-3
  encoder_lr: 5e-5
  weight_decay: 0.01
  lr_scheduler: linear
  warmup: 0.2

trainer:
  # k_fold: 5
  epoch: 300
  eval_epoch: 10
  test_epoch: 10
  model_sort_key: F1
  early_stopping: False
  max_model_num: 5
  use_fp16: True
  use_fgm: False
  use_ema: False
  output_path: "chip2022_output" # 保存路径
  save_evaluations: True
  save_checkpoints: True
  save_predictions: True
