log_file: service_log

random_seed: 2022

use_gpu: True
gpu_ids: 1

port: 8080 # 端口号
url: "/innerapi/ai/python/agent" # 接口名称

dataset:
  reader: # reader必有
    type: XXX_reader
    tokenizer: XXX_tokenizer
    vocab_path: "pretrain_model/vocab.txt"
    padding: max_length
    max_seq_len: 512

# model: # 先创建模型，然后加载权重
#   # 模型参数可随意添加
#   type: XXX_model
#   encoder: # encoder主要针对加载预训练模型和进行分层学习率训练
#     type: bert
#     pretrained_model_dir: "pretrain_model"
#   weight_path: "pretrain_model/model.pth" # 若存在则加载权重

inference_model: "XX_model.pth" # 直接加载模型 model和inference_model 二选一

inference:
  use_fp16: False # 是否使用半精度
  input_data_type: XXXX_input # 接口参数格式